# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user11/work/test_18/test_18.srcs/sources_1/bd/soc_hi/ip/soc_hi_dlmb_v10_1/soc_hi_dlmb_v10_1.xci
# IP: The module: 'soc_hi_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_hi/ip/soc_hi_dlmb_v10_1/soc_hi_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hi_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user11/work/test_18/test_18.srcs/sources_1/bd/soc_hi/ip/soc_hi_dlmb_v10_1/soc_hi_dlmb_v10_1.xci
# IP: The module: 'soc_hi_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_hi/ip/soc_hi_dlmb_v10_1/soc_hi_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hi_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
