# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/work/Basys-3-Master.xdc

# Block Designs: bd/soc_hi/soc_hi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi || ORIG_REF_NAME==soc_hi} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_proc_sys_reset_0_0/soc_hi_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_hi_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_clk_wiz_0/soc_hi_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_clk_wiz_0 || ORIG_REF_NAME==soc_hi_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_microblaze_riscv_0_0/soc_hi_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_hi_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_dlmb_v10_1/soc_hi_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_dlmb_v10_1 || ORIG_REF_NAME==soc_hi_dlmb_v10_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_ilmb_v10_1/soc_hi_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_ilmb_v10_1 || ORIG_REF_NAME==soc_hi_ilmb_v10_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_dlmb_bram_if_cntlr_1/soc_hi_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==soc_hi_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_ilmb_bram_if_cntlr_1/soc_hi_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==soc_hi_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_lmb_bram_1/soc_hi_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_lmb_bram_1 || ORIG_REF_NAME==soc_hi_lmb_bram_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_mdm_1_1/soc_hi_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_mdm_1_1 || ORIG_REF_NAME==soc_hi_mdm_1_1} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_axi_uartlite_0_0/soc_hi_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_axi_uartlite_0_0 || ORIG_REF_NAME==soc_hi_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_hi/ip/soc_hi_axi_smc_0/soc_hi_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_hi_axi_smc_0 || ORIG_REF_NAME==soc_hi_axi_smc_0} -quiet] -quiet

# XDC: /home/user11/work/test_18/test_18.gen/sources_1/bd/soc_hi/soc_hi_ooc.xdc
